
import{firebaseConfig}from'./firebase-config.js';import{initializeApp}from'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';import{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,sendPasswordResetEmail}from'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';import{getDatabase,ref,set,get,update,push,onValue,runTransaction}from'https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js';import{mountUser}from'./user-core.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);let listeners=[],state={loggedIn:false,user:{},settings:{},currentPayment:{},activities:[],transactions:[],fundAccounts:{},fundCodes:{},banks:[]},me=null;const emit=()=>listeners.forEach(f=>f());
async function log(type,title,message){const id=push(ref(db,`activityLogs/${me.uid}`)).key;await set(ref(db,`activityLogs/${me.uid}/${id}`),{type,title,message,createdAt:Date.now()})}
const adapter={getState:()=>state,subscribe:f=>listeners.push(f),login:async(e,p)=>signInWithEmailAndPassword(auth,e,p),register:async d=>{const c=await createUserWithEmailAndPassword(auth,d.email,d.password);await set(ref(db,`users/${c.user.uid}`),{uid:c.user.uid,userCode:'TRG'+Date.now().toString().slice(-7),username:d.username,phone:d.phone,email:d.email,registeredAt:Date.now(),accountStatus:'stopped',activationStatus:'not_submitted',balance:0,commission:0,bonusClaimed:false,invalidAttempts:0,penalty:0,blocked:false,setup:{accountDetail:false,atm:false,activate:false,run:false}})},logout:()=>signOut(auth),forgot:e=>sendPasswordResetEmail(auth,e),
 submitPayment:async utr=>{if(!/^[A-Za-z0-9]{8,30}$/.test(utr))throw Error('Valid UTR required');const id=push(ref(db,'activationPayments')).key,amount=Number(state.settings.activationFee||1999)+Number(state.user.penalty||0);await set(ref(db,`activationPayments/${id}`),{id,uid:me.uid,email:me.email,utr,amount,status:'pending',attempt:Number(state.user.invalidAttempts||0)+1,createdAt:Date.now()});await update(ref(db,`users/${me.uid}`),{activationStatus:'pending',currentPaymentId:id});await log('payment','Payment submitted','Admin verification pending.')},
 verifyActivation:async code=>{if(code!==state.currentPayment.activationCode)throw Error('Invalid activation code');await update(ref(db,`users/${me.uid}`),{activationStatus:'verified',accountStatus:'running',permanentActivationCode:code,activatedAt:Date.now(),'setup/activate':true,'setup/run':true});await log('account','VIP Account Activated','Activation code verified.')},
 ensureFundCode:async k=>{const r=ref(db,`fundSetupCodes/${me.uid}/${k}`),s=await get(r);if(s.exists())return s.val();const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',code=Array.from({length:8},()=>chars[Math.floor(Math.random()*chars.length)]).join('');await set(r,code);return code},
 saveFundAccount:async(k,bank,atm,code)=>{const expected=(await get(ref(db,`fundSetupCodes/${me.uid}/${k}`))).val();if(code.toUpperCase()!==expected)throw Error('Fund code mismatch');const current=state.fundAccounts[k]||[];if(current.length>=10)throw Error('Maximum 10 accounts');const id=push(ref(db,`fundAccounts/${me.uid}/${k}`)).key;await set(ref(db,`fundAccounts/${me.uid}/${k}/${id}`),{...bank,confirm:null,atm,status:'active',createdAt:Date.now()});await update(ref(db,`users/${me.uid}/setup`),{accountDetail:true,atm:true});await log('fund','Fund account added',k+' fund account added.')},
 requestWithdrawal:async(type,amount,details)=>{if(amount<=0||amount>Number(state.user.balance||0)||amount<Number(state.settings.minWithdrawal||0))throw Error('Invalid amount');const id=push(ref(db,'withdrawals')).key;await set(ref(db,`withdrawals/${id}`),{id,uid:me.uid,email:me.email,type,amount,details,status:'pending',createdAt:Date.now()});await log('withdrawal','Withdrawal requested','₹'+amount+' request submitted.')},
 claimBonus:async()=>{if(state.user.accountStatus!=='running')throw Error('Account running required');const tr=await runTransaction(ref(db,`users/${me.uid}/bonusClaimed`),v=>v===true?undefined:true);if(!tr.committed)throw Error('Bonus already claimed');const amount=Number(state.settings.bonusAmount||2000);await runTransaction(ref(db,`users/${me.uid}/balance`),v=>Number(v||0)+amount);const id=push(ref(db,`transactions/${me.uid}`)).key;await set(ref(db,`transactions/${me.uid}/${id}`),{title:'Bonus Claim',type:'bonus',amount,status:'completed',createdAt:Date.now()});await log('bonus','Bonus claimed','₹'+amount+' added to Total Balance.')}
};
onAuthStateChanged(auth,x=>{me=x;state.loggedIn=!!x;emit();if(!x)return;const err=e=>console.error(e);onValue(ref(db,'settings'),s=>{state.settings=s.val()||{};emit()},err);onValue(ref(db,'bankDirectory'),s=>{const v=s.val();state.banks=v?Object.values(v).filter(x=>x.enabled!==false).map(x=>x.name):[];emit()},err);onValue(ref(db,`users/${x.uid}`),s=>{state.user=s.val()||{};const pid=state.user.currentPaymentId;if(pid)onValue(ref(db,`activationPayments/${pid}`),p=>{state.currentPayment=p.val()||{};emit()},err);emit()},err);onValue(ref(db,`activityLogs/${x.uid}`),s=>{state.activities=Object.values(s.val()||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));emit()},err);onValue(ref(db,`transactions/${x.uid}`),s=>{state.transactions=Object.values(s.val()||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));emit()},err);onValue(ref(db,`fundAccounts/${x.uid}`),s=>{const raw=s.val()||{};state.fundAccounts=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Object.values(v||{})]));emit()},err);onValue(ref(db,`fundSetupCodes/${x.uid}`),s=>{state.fundCodes=s.val()||{};emit()},err)});
mountUser(adapter);
