import{firebaseConfig}from"./firebase-config.js";

window.addEventListener("error",e=>console.error("Tiranga Pay error:",e.message,e.filename,e.lineno));
window.addEventListener("unhandledrejection",e=>console.error("Tiranga Pay promise error:",e.reason));

import{initializeApp}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged,sendPasswordResetEmail}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import{getDatabase,ref,set,get,update,push,onValue}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js";
const app=initializeApp(firebaseConfig);const auth=getAuth(app),db=getDatabase(app);
const $=id=>document.getElementById(id),money=n=>"₹"+Number(n||0).toLocaleString("en-IN");let me=null,u={},settings={},payment={},activities=[],transactions=[],captcha="";
const locked=new Set(["gaming","stock","mix","political","outside","performance","history","commission","withdrawal","bonus"]);
const defs=[["gaming","🎮","Gaming Fund","gamingFundRate",15],["stock","📈","Stock Fund","stockFundRate",30],["mix","◔","Mix Fund","mixFundRate",25],["political","🏛","Political Fund","politicalFundRate",10],["outside","🌐","Outside Fund","outsideFundRate",20],["performance","🎯","Performance Bonus","performanceBonusRate",5],["history","📄","Transaction History","",0],["commission","👥","Commission","",0],["withdrawal","👛","Withdrawal","",0],["bonus","🎁","Bonus Claim","",0]];
window.showRegister=()=>{$("loginBox").classList.add("hidden");$("registerBox").classList.remove("hidden");newCaptcha()};window.showLogin=()=>{$("registerBox").classList.add("hidden");$("loginBox").classList.remove("hidden")};
function newCaptcha(){captcha=String(Math.floor(100000+Math.random()*900000));$("captchaView").value=captcha}newCaptcha();
async function adminFeed(title,message,type="activity"){const k=push(ref(db,"adminActivityFeed")).key;await set(ref(db,"adminActivityFeed/"+k),{uid:me?.uid||"",userEmail:me?.email||"",title,message,type,createdAt:Date.now(),unread:true})}
window.registerUser=async()=>{try{if($("regPass").value!==$("regPass2").value)throw Error("Passwords match nahi hain");if($("captchaInput").value.trim()!==captcha)throw Error("Verification code galat hai");const c=await createUserWithEmailAndPassword(auth,$("regEmail").value,$("regPass").value);me=c.user;await set(ref(db,"users/"+c.user.uid),{username:$("regName").value.trim(),phone:$("regPhone").value.trim(),email:c.user.email,registeredAt:Date.now(),accountStatus:"stopped",activationStatus:"not_submitted",balance:0,commission:0,bonusClaimed:false,invalidAttempts:0,penalty:0,blocked:false,setup:{accountDetail:false,atm:false,activate:false,run:false}});await addActivity("account","Registration completed","Your Tiranga Pay account was created.");await adminFeed("New user registered",c.user.email+" created an account","registration")}catch(e){$("regMsg").textContent=e.message;newCaptcha()}};
window.loginUser=async()=>{try{const c=await signInWithEmailAndPassword(auth,$("loginEmail").value,$("loginPass").value);me=c.user;await adminFeed("User login",c.user.email+" logged in","login")}catch(e){$("loginMsg").textContent=e.message}};
window.forgotPassword=async()=>{try{if(!$("loginEmail").value)throw Error("Email enter karein");await sendPasswordResetEmail(auth,$("loginEmail").value);alert("Password reset email sent")}catch(e){alert(e.message)}};window.logoutUser=()=>signOut(auth);
window.goPage=(id,b)=>{document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active")};
function running(){return u.accountStatus==="running"&&!u.blocked}
async function addActivity(type,title,message){const k=push(ref(db,"activityLogs/"+me.uid)).key;await set(ref(db,"activityLogs/"+me.uid+"/"+k),{type,title,message,createdAt:Date.now()})}
function render(){if(!me)return;$("uName").textContent=u.username||"User";$("uId").textContent=me.uid.slice(0,10).toUpperCase();$("bonusTop").textContent=money(settings.bonusAmount||2000);$("balance").textContent=money(u.balance);$("commission").textContent=money(u.commission);$("txCount").textContent=transactions.length;$("activationTitle").textContent=u.blocked?"ID Blocked":running()?"Account Running":"Account Not Activated";$("activationText").textContent=u.blocked?"Contact Support for unblock.":running()?"All eligible options unlocked.":"Complete payment and admin verification.";
const setup=u.setup||{};$("steps").innerHTML=[["Account Detail",!!setup.accountDetail],["ATM Setup",!!setup.atm],["Activate",u.activationStatus==="verified"],["Account Run",running()]].map(([n,d],i)=>`<div class="step"><div class="num">${d?"✓":i+1}</div><b>${n}</b><span class="badge ${d?"":"gray"}">${d?"Completed":"Pending"}</span></div>`).join("");
$("quickGrid").innerHTML=defs.map(([k,i,n,sk,d])=>`<div class="q" onclick="openFeature('${k}','${n}')"><div class="i">${i}</div><b>${n}</b><small>${sk?(settings[sk]??d)+"%":running()?"Available":"🔒 Locked"}</small></div>`).join("");
$("activityList").innerHTML=activities.length?activities.map(a=>`<div class="card item"><b>${a.title}</b><div class="label">${a.message||""}</div><div class="label">${new Date(a.createdAt||0).toLocaleString("en-IN")}</div></div>`).join(""):`<div class="card item">No activity yet.</div>`;
$("txList").innerHTML=transactions.length?transactions.map(t=>`<div class="card item row between"><div><b>${t.title||t.type}</b><div class="label">${new Date(t.createdAt||0).toLocaleString("en-IN")}</div></div><div><b class="amount ${Number(t.amount)>=0?"pos":"neg"}">${Number(t.amount)>=0?"+":""}${money(t.amount)}</b><div class="label">${t.status||"completed"}</div></div></div>`).join(""):`<div class="card item">No transactions yet.</div>`;
$("runStatus").textContent=u.blocked?"ID BLOCKED":running()?"ACCOUNT RUNNING":"ACCOUNT STOPPED";$("runCopy").textContent=running()?"Funds, commission, transactions, withdrawal and bonus claim are active.":u.blocked?"Only Customer Support is available.":"Complete activation steps.";$("runHistory").innerHTML=activities.filter(a=>["account","payment"].includes(a.type)).slice(0,10).map(a=>`<div class="item"><b>${a.title}</b><div class="label">${new Date(a.createdAt||0).toLocaleString("en-IN")}</div></div>`).join("");
$("pName").textContent=u.username||"User";$("pEmail").textContent=u.email||"";$("pPhone").textContent=u.phone||"";$("pStatus").textContent=u.blocked?"Blocked":u.accountStatus||"stopped";renderProfileMenu()}
function renderProfileMenu(){const m=[["Personal Information","personal"],["Bank Details","bank"],["Account Setup Status","setup"],["Bonus Details","bonusdetails"],["Change Password","password"],["Privacy Policy","privacy"],["Terms & Conditions","terms"],["Fund Policy","fundpolicy"],["Withdrawal Policy","withdrawalpolicy"],["Bonus Policy","bonuspolicy"],["Support Policy","supportpolicy"],["Contact Support","support"],["Logout","logout"]];$("profileMenu").innerHTML=m.map(([n,k])=>`<button onclick="profileAction('${k}')">${n} ›</button>`).join("")}
window.openFeature=(k,n)=>{if(locked.has(k)&&!running())return showModal(`<h2>🔒 ${n} Locked</h2><p>Account Activate & Run hone ke baad unlock hoga.</p><button class="btn orange" onclick="openActivation()">Activate Account</button>`);if(k==="withdrawal")return openWithdrawal();if(k==="bonus")return openBonus();if(k==="history")return goPage("transactions",document.querySelectorAll(".nav")[2]);if(k==="commission")return showModal(`<h2>Commission</h2><p>Total: <b>${money(u.commission)}</b></p><p>${settings.commissionPolicy||"Admin-controlled commission records."}</p>`);openFund(k,n)};
function openFund(k,n){const data=u.funds?.[k]||{},rate=settings[k+"FundRate"]??settings[k+"Rate"]??0;showModal(`<h2>${n}</h2><p>Percentage: <b>${rate}%</b></p><p>Available Balance: <b>${money(data.balance)}</b></p><p>Total Commission: <b>${money(data.commission)}</b></p><div class="policy">${settings.fundPolicy||"Fund policy not added."}</div>`)}
window.openActivation=()=>{if(u.blocked)return showModal(`<h2>⛔ ID Blocked</h2><p>4 invalid attempts reached.</p><button class="btn orange" onclick="openSupport()">Contact Support</button>`);const total=Number(settings.activationFee||1999)+Number(u.penalty||0);if(payment.status==="pending")return showModal(`<h2>⏳ Payment Verification Pending</h2><p>${money(payment.amount)} under admin review.</p>`);if(payment.status==="approved")return showModal(`<h2>✅ Payment Approved</h2><p>Activation Code: <b>${payment.activationCode||"Pending"}</b></p><input id="activationCode"><button class="btn" onclick="verifyCode()">Verify & Activate</button>`);showModal(`<h2>Activate Your Account</h2><p>Activation Fee: <b>${money(settings.activationFee||1999)}</b></p><p>Penalty: <b>${money(u.penalty||0)}</b></p><p>Total Payable: <b>${money(total)}</b></p><p>UPI ID: <b>${settings.adminUpiId||"Not set"}</b></p>${settings.paymentQr?`<img src="${settings.paymentQr}" style="max-width:220px;width:100%">`:""}<input id="utrInput" placeholder="UTR / Transaction ID"><textarea id="paymentNote" placeholder="Optional note"></textarea><button class="btn" onclick="submitPayment()">Submit For Verification</button><div class="notice">1st reject: ₹100 penalty. 2nd: total ₹300. 3rd: total ₹600. 4th: ID auto-block.</div>`)};
window.submitPayment=async()=>{const utr=$("utrInput").value.trim();if(!utr)return alert("UTR required");const amount=Number(settings.activationFee||1999)+Number(u.penalty||0);await set(ref(db,"activationPayments/"+me.uid),{uid:me.uid,email:me.email,utr,note:$("paymentNote").value,amount,status:"pending",attempt:Number(u.invalidAttempts||0)+1,createdAt:Date.now()});await update(ref(db,"users/"+me.uid),{activationStatus:"pending"});await addActivity("payment","Activation payment submitted",money(amount)+" verification request sent.");await adminFeed("New payment request",me.email+" submitted "+money(amount),"payment");closeModal()};
window.verifyCode=async()=>{const code=$("activationCode").value.trim();if(!code||code!==payment.activationCode)return alert("Invalid activation code");await update(ref(db,"users/"+me.uid),{activationStatus:"verified",accountStatus:"running",activatedAt:Date.now(),"setup/activate":true,"setup/run":true});await addActivity("account","Account running started","All eligible options unlocked.");await adminFeed("Account activated",me.email+" verified activation code","activation");closeModal()};
function openWithdrawal(){showModal(`<h2>Withdrawal</h2><p>Available Balance: <b>${money(u.balance)}</b></p><p>Minimum: <b>${money(settings.minWithdrawal||0)}</b></p><input id="withdrawAmount" type="number" placeholder="Amount"><select id="withdrawMethod"><option>Bank Account</option><option>UPI</option></select><button class="btn" onclick="requestWithdrawal()">Request Withdrawal</button><div class="policy">${settings.withdrawalPolicy||""}</div>`)}
window.requestWithdrawal=async()=>{const amount=Number($("withdrawAmount").value),min=Number(settings.minWithdrawal||0);if(amount<min||amount>Number(u.balance||0))return alert("Invalid amount");const k=push(ref(db,"withdrawals")).key;await set(ref(db,"withdrawals/"+k),{uid:me.uid,email:me.email,amount,method:$("withdrawMethod").value,status:"pending",createdAt:Date.now()});await addActivity("withdrawal","Withdrawal requested",money(amount)+" request submitted.");await adminFeed("Withdrawal request",me.email+" requested "+money(amount),"withdrawal");closeModal()};
function openBonus(){showModal(`<h2>Bonus Claim</h2><p>Available: <b>${money(settings.bonusAmount||2000)}</b></p><p>Status: ${u.bonusClaimed?"Claimed":"Eligible"}</p><button class="btn" onclick="claimBonus()" ${u.bonusClaimed?"disabled":""}>Claim Bonus</button><div class="policy">${settings.bonusPolicy||""}</div>`)}
window.claimBonus=async()=>{const k=push(ref(db,"bonusClaims")).key;await set(ref(db,"bonusClaims/"+k),{uid:me.uid,email:me.email,amount:Number(settings.bonusAmount||2000),status:"pending",createdAt:Date.now()});await update(ref(db,"users/"+me.uid),{bonusClaimed:true,bonusClaimedAt:Date.now()});await addActivity("bonus","Bonus claim submitted",money(settings.bonusAmount||2000)+" claim sent.");await adminFeed("Bonus claim",me.email+" submitted bonus claim","bonus");closeModal()};
window.profileAction=async k=>{if(k==="logout")return logoutUser();if(k==="support")return openSupport();if(k==="password"){await sendPasswordResetEmail(auth,me.email);return alert("Password reset email sent")};const map={privacy:["Privacy Policy",settings.privacyPolicy],terms:["Terms & Conditions",settings.terms],fundpolicy:["Fund Policy",settings.fundPolicy],withdrawalpolicy:["Withdrawal Policy",settings.withdrawalPolicy],bonuspolicy:["Bonus Policy",settings.bonusPolicy],supportpolicy:["Support Policy",settings.supportPolicy],personal:["Personal Information",`Username: ${u.username}<br>Email: ${u.email}<br>Mobile: ${u.phone}`],bank:["Bank Details",`Account Holder: ${u.bank?.holder||"Not added"}<br>Account: ${u.bank?.account||""}<br>IFSC: ${u.bank?.ifsc||""}`],setup:["Account Setup Status",JSON.stringify(u.setup||{},null,2)],bonusdetails:["Bonus Details",`Bonus: ${money(settings.bonusAmount||2000)}<br>Claimed: ${u.bonusClaimed?"Yes":"No"}`]};const [t,c]=map[k]||["Details",""];showModal(`<h2>${t}</h2><div class="policy">${c||"Not added"}</div>`)};
window.openSupport=()=>showModal(`<h2>Customer Support</h2><div class="policy">${settings.supportContact||"Support details not set"}</div>${settings.telegramLink?`<a class="btn" href="${settings.telegramLink}" target="_blank">Open Telegram</a>`:""}`);
window.showModal=h=>{$("modalBody").innerHTML=h;$("modal").classList.remove("hidden")};window.closeModal=()=>$("modal").classList.add("hidden");
onAuthStateChanged(auth,x=>{me=x;$("authView").classList.toggle("hidden",!!x);$("mainView").classList.toggle("hidden",!x);if(!x)return;onValue(ref(db,"settings"),s=>{settings=s.val()||{};render()});onValue(ref(db,"users/"+x.uid),s=>{u=s.val()||{};render()});onValue(ref(db,"activationPayments/"+x.uid),s=>{payment=s.val()||{};render()});onValue(ref(db,"activityLogs/"+x.uid),s=>{activities=Object.values(s.val()||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));render()});onValue(ref(db,"transactions/"+x.uid),s=>{transactions=Object.values(s.val()||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));render()})});