
const FUND_DEFS=[['gaming','🎮','Gaming Fund','gamingFundRate',15],['stock','📈','Stock Fund','stockFundRate',30],['mix','◔','Mix Fund','mixFundRate',25],['political','🏛','Political Fund','politicalFundRate',10],['outside','🌐','Outside Fund','outsideFundRate',20],['performance','🎯','Performance Bonus','performanceBonusRate',5],['history','📄','Transaction History','',0],['commission','👥','Commission','',0],['withdrawal','👛','Withdrawal','',0],['bonus','🎁','Bonus Claim','',0]];
export function mountUser(adapter){
 const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');let state=adapter.getState(),captcha='';
 const el=(id,fn)=>$(id)?.addEventListener('click',fn);const activated=()=>!state.user.blocked&&state.user.accountStatus==='running'&&state.user.activationStatus==='verified';
 const modal=h=>{$('modalBody').innerHTML=h;$('modal').classList.remove('hidden');bindModal()};const close=()=>$('modal').classList.add('hidden');
 function newCaptcha(){captcha=String(Math.floor(100000+Math.random()*900000));$('captchaShow').value=captcha}newCaptcha();
 function goPage(id,b){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));if(b)b.classList.add('active')}
 document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>goPage(b.dataset.page,b)));
 el('showRegBtn',()=>{$('loginBox').classList.add('hidden');$('registerBox').classList.remove('hidden');newCaptcha()});el('showLoginBtn',()=>{$('registerBox').classList.add('hidden');$('loginBox').classList.remove('hidden')});
 el('supportAuthBtn',()=>openSupport());el('forgotBtn',async()=>{try{await adapter.forgot($('le').value.trim());alert('Password reset email sent')}catch(e){alert(e.message)}});
 el('loginBtn',async()=>{try{await adapter.login($('le').value.trim(),$('lp').value)}catch(e){$('lm').textContent=e.message}});
 el('registerBtn',async()=>{try{if($('rp').value!==$('rp2').value)throw Error('Passwords match nahi hain');if($('captchaEnter').value.trim()!==captcha)throw Error('Verification code galat hai');await adapter.register({username:$('rn').value.trim(),phone:$('rphone').value.trim(),email:$('re').value.trim(),password:$('rp').value})}catch(e){$('rm').textContent=e.message;newCaptcha()}});
 el('logoutBtn',()=>adapter.logout());el('activationBtn',openActivation);el('closeModalBtn',close);
 function render(){
  state=adapter.getState();const u=state.user||{},p=state.currentPayment||{},s=state.settings||{};
  const logged=!!state.loggedIn;$('authView').classList.toggle('hidden',logged);$('mainView').classList.toggle('hidden',!logged);if(!logged)return;
  $('uName').textContent=u.username||'User';$('uId').textContent=(u.userCode||u.uid||'').slice(0,12).toUpperCase();$('bonusTop').textContent=money(s.bonusAmount||2000);$('balance').textContent=money(u.balance);$('commission').textContent=money(u.commission);$('txCount').textContent=(state.transactions||[]).length;
  const act=activated();$('activationCard').classList.toggle('hidden',act);$('vipCard').classList.toggle('hidden',!act);$('vipCode').textContent=u.permanentActivationCode||p.activationCode||'—';
  if(!act){$('activationTitle').textContent=u.blocked?'ID Blocked':p.status==='approved'?'Payment Approved – Verify Code':p.status==='pending'?'Admin Verification Pending':p.status==='rejected'?'Payment Rejected':'Account Not Activated';
   $('activationText').textContent=u.blocked?'Customer Support available.':p.status==='pending'?'Payment submitted. Admin verification pending.':p.status==='approved'?'Code नीचे डालकर account activate करें.':p.status==='rejected'?`Reason: ${p.rejectReason||'Invalid UTR'} · Penalty: ${money(u.penalty)} · Total: ${money(Number(s.activationFee||1999)+Number(u.penalty||0))}`:'Complete payment and submit UTR.';
   $('activationCodeText').textContent=p.status==='approved'&&p.activationCode?'Verification Code: '+p.activationCode:'';$('activationBtn').textContent=p.status==='approved'?'Verify Code':p.status==='pending'?'Pending':p.status==='rejected'?'Pay Again':'Activate';$('activationBtn').disabled=p.status==='pending'}
  const setup=u.setup||{};$('steps').innerHTML=[['Account Detail',!!setup.accountDetail],['ATM Setup',!!setup.atm],['Activate',act],['Account Run',act]].map(([n,d],i)=>`<div class="step"><div class="num">${d?'✓':i+1}</div><b>${n}</b><span class="badge ${d?'':'gray'}">${d?'Completed':'Pending'}</span></div>`).join('');
  $('quickGrid').innerHTML=FUND_DEFS.map(([k,i,n,sk,d])=>`<button class="q" data-feature="${k}" data-name="${n}"><div class="i">${i}</div><b>${n}</b><small>${sk?(s[sk]??d)+'%':act?'Available':'🔒 Locked'}</small></button>`).join('');document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>openFeature(b.dataset.feature,b.dataset.name)));
  $('activityList').innerHTML=(state.activities||[]).map(a=>`<div class="card item"><b>${a.title}</b><div class="label">${a.message||''}</div></div>`).join('')||'<div class="card item">No activity.</div>';
  $('txList').innerHTML=(state.transactions||[]).map(t=>`<div class="card item row between"><div><b>${t.title}</b><div class="label">${t.status||'completed'}</div></div><b>${Number(t.amount)>=0?'+':''}${money(t.amount)}</b></div>`).join('')||'<div class="card item">No transactions.</div>';
  $('runStatus').textContent=u.blocked?'ID BLOCKED':act?'ACCOUNT RUNNING':'ACCOUNT STOPPED';$('runCopy').textContent=act?'All eligible options unlocked.':'Activation code verify करें.';$('runCode').textContent=act?'VIP Code: '+(u.permanentActivationCode||p.activationCode||'—'):'';
  $('pName').textContent=u.username||'';$('pEmail').textContent=u.email||'';$('pPhone').textContent=u.phone||'';$('pStatus').textContent=u.blocked?'Blocked':u.accountStatus||'stopped';
  $('profileMenu').innerHTML=[['Personal Information','personal'],['Fund Bank Accounts','bank'],['Change Password','password'],['Privacy Policy','privacy'],['Terms & Conditions','terms'],['Fund Policy','fundpolicy'],['Withdrawal Policy','withdrawalpolicy'],['Bonus Policy','bonuspolicy'],['Support Policy','supportpolicy'],['Customer Support','support']].map(([n,k])=>`<button data-profile="${k}">${n} ›</button>`).join('');document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>profileAction(b.dataset.profile)));
 }
 async function openActivation(){const u=state.user,p=state.currentPayment||{},s=state.settings;if(u.blocked)return modal('<h2>ID Blocked</h2><p>Customer Support से संपर्क करें.</p>');if(activated())return modal(`<h2>VIP Verified</h2><p>Permanent Activation Code: <b>${u.permanentActivationCode||p.activationCode}</b></p>`);if(p.status==='pending')return modal('<h2>Admin Verification Pending</h2><p>Payment form दोबारा नहीं खुलेगा.</p>');if(p.status==='approved')return modal(`<h2>Verify Activation Code</h2><div class="notice">Code: <b>${p.activationCode}</b></div><input id="verifyCode" placeholder="Enter verification code"><button class="btn" id="verifyBtn">Verify & Activate</button>`);const total=Number(s.activationFee||1999)+Number(u.penalty||0);modal(`<h2>${p.status==='rejected'?'Pay Again':'Activate Account'}</h2><p>Activation Fee: <b>${money(s.activationFee||1999)}</b></p><p>Penalty: <b>${money(u.penalty)}</b></p><p>Total Payable: <b>${money(total)}</b></p><p>UPI: <b>${s.adminUpiId||'Not set'}</b></p><input id="utr" placeholder="UTR / Transaction ID"><button class="btn" id="submitPayBtn">Submit Payment</button>`)}
 async function openFeature(k,n){if(!activated()){const p=state.currentPayment||{};if(p.status==='pending')return modal('<h2>Admin Verification Pending</h2><p>Payment already submitted.</p>');if(p.status==='approved')return openActivation();return openActivation()}if(['gaming','stock','mix','political','outside','performance'].includes(k))return openFund(k,n);if(k==='withdrawal')return withdrawal();if(k==='bonus')return bonus();if(k==='history')return goPage('transactions',document.querySelector('[data-page="transactions"]'));if(k==='commission')return modal(`<h2>Commission</h2><p>Total: <b>${money(state.user.commission)}</b></p>`)}
 function openFund(k,n){const arr=(state.fundAccounts?.[k]||[]),code=state.fundCodes?.[k];modal(`<h2>${n}</h2><p>Accounts: <b>${arr.length}/10</b></p><button class="btn" id="addFundBtn" data-fund="${k}" data-name="${n}">Add Bank Account</button>${arr.map(a=>`<div class="card account-card"><b>${a.holder}</b><div class="label">${a.bank} · ****${String(a.account).slice(-4)}</div></div>`).join('')}${code?`<div class="notice">Fund Code: <b>${code}</b></div>`:''}`)}
 function fundStep1(k,n){if((state.fundAccounts?.[k]||[]).length>=10)return alert('Maximum 10 accounts');modal(`<h2>${n} – Setup 1</h2><div class="form"><input id="fh" placeholder="Account Holder Name"><input id="fa" placeholder="Account Number"><input id="fac" placeholder="Confirm Account Number"><input id="fp" placeholder="Phone Number"><input id="fi" placeholder="IFSC Code"><input id="fb" list="bankList" placeholder="Bank Name"><datalist id="bankList">${(state.banks||[]).map(b=>`<option value="${b}"></option>`).join('')}</datalist><button class="btn" id="fundStep2Btn">Continue</button></div>`);$('fundStep2Btn').dataset.fund=k;$('fundStep2Btn').dataset.name=n}
 function fundStep2(k,n){const d={holder:$('fh').value.trim(),account:$('fa').value.trim(),confirm:$('fac').value.trim(),phone:$('fp').value.trim(),ifsc:$('fi').value.trim().toUpperCase(),bank:$('fb').value.trim()};if(!d.holder||!/^[0-9]{6,18}$/.test(d.account)||d.account!==d.confirm||!/^[6-9][0-9]{9}$/.test(d.phone)||!/^[A-Z]{4}0[A-Z0-9]{6}$/.test(d.ifsc)||!state.banks.includes(d.bank))return alert('Valid bank details भरें');state.draftBank=d;modal(`<h2>${n} – Setup 2</h2><div class="form"><input id="cardName" placeholder="ATM Card Holder Name"><input id="last4" maxlength="4" placeholder="Last 4 digits"><input id="expiry" placeholder="MM/YY"><select id="cardType"><option>Debit Card</option><option>Credit Card</option></select><div class="notice">ATM PIN, CVV और full card number store नहीं होगा.</div><button class="btn" id="fundStep3Btn">Continue</button></div>`);$('fundStep3Btn').dataset.fund=k;$('fundStep3Btn').dataset.name=n}
 async function fundStep3(k,n){if(!/^[0-9]{4}$/.test($('last4').value)||!/^(0[1-9]|1[0-2])\/[0-9]{2}$/.test($('expiry').value))return alert('Valid ATM details');state.draftAtm={holder:$('cardName').value,last4:$('last4').value,expiry:$('expiry').value,type:$('cardType').value};const code=await adapter.ensureFundCode(k);modal(`<h2>${n} – Setup 3</h2><div class="notice"><b>${code}</b><br>इस कोड को सुरक्षित रखें। इसी fund में नया account जोड़ने के लिए यही code आवश्यक है.<br><br>Keep this code safe. The same code is required for another account in this fund.</div><input id="confirmFundCode" placeholder="Enter same code"><button class="btn" id="saveFundBtn">Verify & Save</button>`);$('saveFundBtn').dataset.fund=k}
 function withdrawal(){modal(`<h2>Withdrawal</h2><div class="tabs"><button class="active" id="bankTab">Bank Account</button><button id="upiTab">UPI</button></div><div id="withdrawFields"></div>`);renderWithdrawal('bank')}
 function renderWithdrawal(type){document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));$(type==='bank'?'bankTab':'upiTab').classList.add('active');$('withdrawFields').innerHTML=type==='upi'?`<div class="form"><input id="wa" type="number" placeholder="Amount"><input id="upiId" placeholder="name@bank"><button class="btn" id="withdrawSubmit" data-type="upi">Request</button></div>`:`<div class="form"><input id="wa" type="number" placeholder="Amount"><input id="wh" placeholder="Holder Name"><input id="wan" placeholder="Account Number"><input id="wac" placeholder="Confirm Account Number"><input id="wifsc" placeholder="IFSC"><input id="wphone" placeholder="Mobile"><input id="wbank" list="bankList2" placeholder="Bank Name"><datalist id="bankList2">${state.banks.map(b=>`<option value="${b}"></option>`).join('')}</datalist><button class="btn" id="withdrawSubmit" data-type="bank">Request</button></div>`;bindModal()}
 function bonus(){modal(`<h2>Bonus Claim</h2><p>Available: <b>${money(state.settings.bonusAmount||2000)}</b></p><p>${state.user.bonusClaimed?'Already claimed':'One-time claim सीधे Total Balance में जुड़ेगा.'}</p><button class="btn" id="bonusClaimBtn" ${state.user.bonusClaimed?'disabled':''}>${state.user.bonusClaimed?'Already Claimed':'Claim Bonus'}</button>`)}
 function profileAction(k){if(k==='support')return openSupport();if(k==='password')return adapter.forgot(state.user.email).then(()=>alert('Reset email sent'));const map={privacy:['Privacy Policy',state.settings.privacyPolicy],terms:['Terms & Conditions',state.settings.terms],fundpolicy:['Fund Policy',state.settings.fundPolicy],withdrawalpolicy:['Withdrawal Policy',state.settings.withdrawalPolicy],bonuspolicy:['Bonus Policy',state.settings.bonusPolicy],supportpolicy:['Support Policy',state.settings.supportPolicy],personal:['Personal Information',`Username: ${state.user.username}<br>Email: ${state.user.email}<br>Mobile: ${state.user.phone}`],bank:['Fund Bank Accounts','हर fund के अंदर अलग bank accounts उपलब्ध हैं.']};const [t,c]=map[k]||['Details',''];modal(`<h2>${t}</h2><div class="policy">${c||'Not added'}</div>`)}
 function openSupport(){modal(`<h2>Customer Support</h2><div class="policy">${state.settings.supportContact||'Support details not set'}</div>`)}
 function bindModal(){
  $('closeModalBtn')?.addEventListener('click',close);
  $('submitPayBtn')?.addEventListener('click',async()=>{try{await adapter.submitPayment($('utr').value.trim());close()}catch(e){alert(e.message)}});
  $('verifyBtn')?.addEventListener('click',async()=>{try{await adapter.verifyActivation($('verifyCode').value.trim());close()}catch(e){alert(e.message)}});
  $('addFundBtn')?.addEventListener('click',e=>fundStep1(e.currentTarget.dataset.fund,e.currentTarget.dataset.name));
  $('fundStep2Btn')?.addEventListener('click',e=>fundStep2(e.currentTarget.dataset.fund,e.currentTarget.dataset.name));
  $('fundStep3Btn')?.addEventListener('click',e=>fundStep3(e.currentTarget.dataset.fund,e.currentTarget.dataset.name));
  $('saveFundBtn')?.addEventListener('click',async e=>{try{await adapter.saveFundAccount(e.currentTarget.dataset.fund,state.draftBank,state.draftAtm,$('confirmFundCode').value.trim());close()}catch(err){alert(err.message)}});
  $('bankTab')?.addEventListener('click',()=>renderWithdrawal('bank'));$('upiTab')?.addEventListener('click',()=>renderWithdrawal('upi'));
  $('withdrawSubmit')?.addEventListener('click',async e=>{try{const type=e.currentTarget.dataset.type,amount=Number($('wa').value);let details;if(type==='upi'){const upi=$('upiId').value.trim();if(!/^[a-zA-Z0-9._-]{2,256}@[a-zA-Z]{2,64}$/.test(upi))throw Error('Valid UPI ID');details={upi}}else{const acc=$('wan').value.trim(),bank=$('wbank').value.trim();if(!$('wh').value.trim()||!/^[0-9]{6,18}$/.test(acc)||acc!==$('wac').value.trim()||!/^[A-Z]{4}0[A-Z0-9]{6}$/.test($('wifsc').value.trim().toUpperCase())||!/^[6-9][0-9]{9}$/.test($('wphone').value.trim())||!state.banks.includes(bank))throw Error('Valid bank details');details={holder:$('wh').value.trim(),account:acc,ifsc:$('wifsc').value.trim().toUpperCase(),phone:$('wphone').value.trim(),bank}}await adapter.requestWithdrawal(type,amount,details);close()}catch(err){alert(err.message)}});
  $('bonusClaimBtn')?.addEventListener('click',async()=>{try{await adapter.claimBonus();close()}catch(e){alert(e.message)}});
 }
 adapter.subscribe(()=>{state=adapter.getState();render()});render()
}
