
export const ADMIN_MENU=[['dashboard','⌂ Dashboard'],['users','👥 Users List'],['pending','▣ Pending Payments'],['approved','✓ Approved Payments'],['rejected','✕ Rejected Payments'],['codes','▣ Activation Codes'],['penalties','⚠ Penalty & Block History'],['funds','▣ Fund Management'],['fundaccounts','▤ User Fund Accounts'],['ledger','▦ Commission & Ledger'],['transactionsadmin','▤ Transaction History'],['withdrawals','♜ Withdrawal Management'],['bonusadmin','🎁 Bonus Management'],['policies','▣ Policies & App Content'],['notifications','🔔 Notifications & Activity'],['settings','⚙ General Settings'],['banks','🏦 All India Bank Directory'],['audit','▤ Audit Logs']];
export function mountAdmin(adapter){
 const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');let state=adapter.getState(),listenersBound=false;
 $('menu').innerHTML=ADMIN_MENU.map(([k,n],i)=>`<button data-panel="${k}" class="${i?'':'active'}">${n}</button>`).join('');document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.panel,b)));
 $('adminLoginBtn').addEventListener('click',async()=>{try{await adapter.login($('ae').value.trim(),$('ap').value)}catch(e){$('am').textContent=e.message}});$('adminLogoutBtn').addEventListener('click',()=>adapter.logout());
 $('addLedgerBtn').addEventListener('click',()=>adapter.addLedger($('luid').value.trim(),$('ltitle').value,$('ltype').value,Number($('lamount').value)).catch(e=>alert(e.message)));
 $('savePoliciesBtn').addEventListener('click',()=>adapter.savePolicies({fundPolicy:$('fundPolicy').value,privacyPolicy:$('privacyPolicy').value,terms:$('terms').value,withdrawalPolicy:$('withdrawalPolicy').value,bonusPolicy:$('bonusPolicy').value,supportPolicy:$('supportPolicy').value,supportContact:$('supportContact').value,telegramLink:$('telegramLink').value}).then(()=>alert('Saved')));
 $('saveSettingsBtn').addEventListener('click',()=>adapter.saveSettings({activationFee:Number($('activationFee').value),adminUpiId:$('adminUpiId').value,paymentQr:$('paymentQr').value,minWithdrawal:Number($('minWithdrawal').value),bonusAmount:Number($('bonusAmount').value)}).then(()=>alert('Saved')));
 $('addBankBtn').addEventListener('click',()=>adapter.addBank($('newBankName').value.trim()).then(()=>{$('newBankName').value=''}).catch(e=>alert(e.message)));
 function showPanel(id,b){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('[data-panel]').forEach(x=>x.classList.remove('active'));b?.classList.add('active')}
 function render(){
  state=adapter.getState();$('loginView').classList.toggle('hidden',state.loggedIn);$('panelView').classList.toggle('hidden',!state.loggedIn);if(!state.loggedIn)return;$('adminIdentity').textContent=state.adminEmail||'';$('unread').textContent=(state.feed||[]).filter(x=>x.unread).length;
  const U=Object.values(state.users||{}),P=Object.values(state.payments||{}),W=Object.values(state.withdrawals||{}),T=Object.values(state.transactions||{}).flatMap(x=>Object.values(x||{})),F=Object.values(state.fundAccounts||{}).flatMap(x=>Object.values(x||{}).flatMap(y=>Object.values(y||{})));
  const metrics=[['Total Users',U.length],['Running Users',U.filter(x=>x.accountStatus==='running'&&!x.blocked).length],['Total Balance',money(U.reduce((a,x)=>a+Number(x.balance||0),0))],['Total Commission',money(U.reduce((a,x)=>a+Number(x.commission||0),0))],['Total Transactions',T.length],['Pending Payments',P.filter(x=>x.status==='pending').length],['Approved Payments',P.filter(x=>x.status==='approved').length],['Rejected Payments',P.filter(x=>x.status==='rejected').length],['Pending Withdrawals',W.filter(x=>x.status==='pending').length],['Paid Withdrawals',W.filter(x=>x.status==='paid').length],['Bonus Claimed',U.filter(x=>x.bonusClaimed).length],['Total Fund Accounts',F.length],['Blocked Users',U.filter(x=>x.blocked).length]];
  $('kpis').innerHTML=metrics.map(([n,v])=>`<div class="card kpi"><div class="label" style="color:#d0d5dd">${n}</div><b>${v}</b></div>`).join('');
  $('usersBody').innerHTML=Object.entries(state.users||{}).map(([id,u])=>`<tr><td>${u.username||id.slice(0,8)}</td><td>${u.email||''}</td><td>${u.blocked?'Blocked':u.accountStatus||'stopped'}</td><td>${u.activationStatus||'none'}</td><td>${u.invalidAttempts||0}/4</td><td>${money(u.penalty)}</td><td>${money(u.balance)}</td><td>${money(u.commission)}</td><td><button class="action" data-user="${id}" data-act="run">Run</button> <button class="action orange" data-user="${id}" data-act="stop">Stop</button> <button class="action red" data-user="${id}" data-act="block">${u.blocked?'Unblock':'Block'}</button> <button class="action" data-user="${id}" data-act="edit">Edit</button></td></tr>`).join('')||'<tr><td colspan="9">No users.</td></tr>';
  const pcard=([id,p])=>`<div class="feeditem"><b>${p.email||p.uid}</b><div class="label">${money(p.amount)} · UTR ${p.utr||''} · Attempt ${p.attempt||1}/4</div><span class="badge ${p.status==='pending'?'orange':p.status==='rejected'?'red':''}">${p.status}</span>${p.activationCode?` <span class="badge">Code: ${p.activationCode}</span>`:''}${p.rejectReason?`<div class="label">Reason: ${p.rejectReason}</div>`:''}${p.status==='pending'?`<div><button class="action" data-pay="${id}" data-status="approved">Approve</button> <button class="action red" data-pay="${id}" data-status="rejected">Reject Invalid UTR</button></div>`:''}</div>`;
  const all=Object.entries(state.payments||{}).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0)),pending=all.filter(x=>x[1].status==='pending'),approved=all.filter(x=>x[1].status==='approved'),rejected=all.filter(x=>x[1].status==='rejected');
  $('pendingBody').innerHTML=pending.map(pcard).join('')||'No pending payments.';$('approvedBody').innerHTML=approved.map(pcard).join('')||'No approved payments.';$('rejectedBody').innerHTML=rejected.map(pcard).join('')||'No rejected payments.';$('dashPayments').innerHTML=pending.slice(0,5).map(pcard).join('')||'No pending payments.';
  $('codesBody').innerHTML=approved.map(([_,p])=>`<div class="feeditem"><b>${p.email||p.uid}</b><div>Activation Code: <b>${p.activationCode||'—'}</b></div></div>`).join('')||'No activation codes.';
  $('penaltiesBody').innerHTML=Object.entries(state.users||{}).filter(([_,u])=>u.invalidAttempts||u.blocked).map(([id,u])=>`<div class="feeditem"><b>${u.username||u.email||id}</b><div>Attempts ${u.invalidAttempts||0}/4 · Penalty ${money(u.penalty)}</div><span class="badge ${u.blocked?'red':'orange'}">${u.blocked?'Blocked':'Active'}</span></div>`).join('')||'No penalties.';
  $('withdrawalsBody').innerHTML=Object.entries(state.withdrawals||{}).map(([id,w])=>`<div class="feeditem"><b>${w.email||w.uid}</b><div>${money(w.amount)} · ${w.type} · ${w.status}</div>${w.status==='pending'?`<button class="action" data-with="${id}" data-wstatus="approved">Approve</button> <button class="action red" data-with="${id}" data-wstatus="rejected">Reject</button>`:''}${w.status==='approved'?`<button class="action orange" data-with="${id}" data-wstatus="processing">Processing</button>`:''}${w.status==='processing'?`<button class="action" data-with="${id}" data-wstatus="paid">Paid</button>`:''}</div>`).join('')||'No withdrawals.';
  const fundRows=[];Object.entries(state.fundAccounts||{}).forEach(([uid,fs])=>Object.entries(fs||{}).forEach(([fund,accs])=>Object.values(accs||{}).forEach(a=>fundRows.push(`<div class="feeditem"><b>${state.users[uid]?.username||state.users[uid]?.email||uid} · ${fund}</b><div>${a.holder} · ${a.bank} · ****${String(a.account).slice(-4)}</div></div>`))));$('fundAccountsBody').innerHTML=fundRows.join('')||'No fund accounts.';
  $('allTransactionsBody').innerHTML=Object.entries(state.transactions||{}).flatMap(([uid,items])=>Object.values(items||{}).map(t=>`<div class="feeditem"><b>${state.users[uid]?.username||state.users[uid]?.email||uid}</b><div>${t.title||t.type} · ${money(t.amount)}</div></div>`)).join('')||'No transactions.';
  $('bonusUsersBody').innerHTML=Object.entries(state.users||{}).map(([id,u])=>`<div class="feeditem"><b>${u.username||u.email||id}</b><div>Claimed: ${u.bonusClaimed?'Yes':'No'} · Balance: ${money(u.balance)}</div><button class="action" data-bonus="${id}">Add Bonus</button>${u.bonusClaimed?` <button class="action red" data-resetbonus="${id}">Reset Claim</button>`:''}</div>`).join('');
  $('recentFeed').innerHTML=(state.feed||[]).slice(0,6).map(x=>`<div class="feeditem"><b>${x.title}</b><div class="label">${x.message||''}</div></div>`).join('')||'No activities.';$('adminFeed').innerHTML=(state.feed||[]).map(x=>`<div class="feeditem"><b>${x.title}</b><div>${x.message||''}</div></div>`).join('')||'No activities.';$('auditBody').innerHTML=(state.audits||[]).map(x=>`<div class="feeditem"><b>${x.action}</b></div>`).join('')||'No audits.';
  const fundCounts={};Object.values(state.fundAccounts||{}).forEach(fs=>Object.entries(fs||{}).forEach(([f,a])=>fundCounts[f]=(fundCounts[f]||0)+Object.keys(a||{}).length));$('topFunds').innerHTML=Object.entries(fundCounts).map(([f,c])=>`<div class="feeditem"><b>${f}</b><span class="badge">${c}</span></div>`).join('')||'No fund accounts.';
  $('fundForm').innerHTML=[['gamingFundRate','Gaming Fund %',15],['stockFundRate','Stock Fund %',30],['mixFundRate','Mix Fund %',25],['politicalFundRate','Political Fund %',10],['outsideFundRate','Outside Fund %',20],['performanceBonusRate','Performance Bonus %',5]].map(([id,n,d])=>`<label>${n}<input id="${id}" type="number" value="${state.settings[id]??d}"></label>`).join('')+'<button class="btn" id="saveFundsBtn">Save Fund Settings</button>';
  [['fundPolicy','fundPolicy'],['privacyPolicy','privacyPolicy'],['terms','terms'],['withdrawalPolicy','withdrawalPolicy'],['bonusPolicy','bonusPolicy'],['supportPolicy','supportPolicy'],['supportContact','supportContact'],['telegramLink','telegramLink'],['activationFee','activationFee'],['adminUpiId','adminUpiId'],['paymentQr','paymentQr'],['minWithdrawal','minWithdrawal'],['bonusAmount','bonusAmount']].forEach(([id,k])=>{if($(id))$(id).value=state.settings[k]??''});
  $('banksBody').innerHTML=(state.banks||[]).map(b=>`<div class="feeditem row between"><span>${b.name}</span><button class="action ${b.enabled===false?'':'red'}" data-bank="${b.id}" data-enabled="${b.enabled===false}">${b.enabled===false?'Enable':'Disable'}</button></div>`).join('');
  bindActions()
 }
 function bindActions(){document.querySelectorAll('[data-pay]').forEach(b=>b.addEventListener('click',()=>adapter.reviewPayment(b.dataset.pay,b.dataset.status)));document.querySelectorAll('[data-with]').forEach(b=>b.addEventListener('click',()=>adapter.setWithdrawal(b.dataset.with,b.dataset.wstatus)));document.querySelectorAll('[data-user]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.user,a=b.dataset.act;if(a==='run')adapter.setUserState(id,'running');if(a==='stop')adapter.setUserState(id,'stopped');if(a==='block')adapter.toggleBlock(id);if(a==='edit')adapter.editUser(id)}));document.querySelectorAll('[data-bonus]').forEach(b=>b.addEventListener('click',()=>adapter.addBonus(b.dataset.bonus)));document.querySelectorAll('[data-resetbonus]').forEach(b=>b.addEventListener('click',()=>adapter.resetBonus(b.dataset.resetbonus)));document.querySelectorAll('[data-bank]').forEach(b=>b.addEventListener('click',()=>adapter.toggleBank(b.dataset.bank,b.dataset.enabled==='true')));$('saveFundsBtn')?.addEventListener('click',()=>adapter.saveFunds({gamingFundRate:Number($('gamingFundRate').value),stockFundRate:Number($('stockFundRate').value),mixFundRate:Number($('mixFundRate').value),politicalFundRate:Number($('politicalFundRate').value),outsideFundRate:Number($('outsideFundRate').value),performanceBonusRate:Number($('performanceBonusRate').value)}))}
 adapter.subscribe(()=>{state=adapter.getState();render()});render()
}
