
import{firebaseConfig}from'./firebase-config.js';import{initializeApp}from'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';import{getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';import{getDatabase,ref,get,set,update,push,onValue,runTransaction}from'https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js';import{mountAdmin}from'./admin-core.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app);let listeners=[],me=null,state={loggedIn:false,adminEmail:'',users:{},payments:{},withdrawals:{},settings:{},feed:[],audits:[],fundAccounts:{},transactions:{},banks:[]};const emit=()=>listeners.forEach(f=>f());const audit=async(action,details={})=>{const id=push(ref(db,'auditLogs')).key;await set(ref(db,`auditLogs/${id}`),{action,details,adminEmail:me.email,createdAt:Date.now()})};
const adapter={getState:()=>state,subscribe:f=>listeners.push(f),login:async(e,p)=>signInWithEmailAndPassword(auth,e,p),logout:()=>signOut(auth),
 reviewPayment:async(id,status)=>{const p=state.payments[id];if(!p||p.status!=='pending')return alert('Payment already processed');const claim=await runTransaction(ref(db,`activationPayments/${id}/status`),v=>v==='pending'?status:undefined);if(!claim.committed)return alert('Payment already processed');if(status==='approved'){const code='TP-'+Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Date.now().toString().slice(-4);await update(ref(db,`activationPayments/${id}`),{activationCode:code,reviewedAt:Date.now(),reviewedBy:me.uid});await update(ref(db,`users/${p.uid}`),{activationStatus:'approved',currentPaymentId:id});await audit('PAYMENT_APPROVED',{id,uid:p.uid,code});alert('Approved. Code: '+code)}else{const u=state.users[p.uid]||{},next=Math.min(4,Number(u.invalidAttempts||0)+1),pen=next===1?100:next===2?300:next===3?600:Number(u.penalty||600),blocked=next>=4,reason=prompt('Reject reason','Invalid/Fake UTR');await update(ref(db,`activationPayments/${id}`),{rejectReason:reason||'Invalid/Fake UTR',reviewedAt:Date.now(),reviewedBy:me.uid});await update(ref(db,`users/${p.uid}`),{activationStatus:'rejected',invalidAttempts:next,penalty:pen,blocked,accountStatus:'stopped',currentPaymentId:id});await audit('PAYMENT_REJECTED',{id,uid:p.uid,next,pen,blocked});alert(blocked?'Rejected and blocked':'Rejected. Penalty updated')}},
 setWithdrawal:async(id,status)=>{await update(ref(db,`withdrawals/${id}`),{status,updatedAt:Date.now(),updatedBy:me.uid});await audit('WITHDRAWAL_'+status.toUpperCase(),{id});alert('Withdrawal '+status)},
 setUserState:async(id,s)=>update(ref(db,`users/${id}`),{accountStatus:s}),toggleBlock:async id=>{const u=state.users[id];await update(ref(db,`users/${id}`),{blocked:!u.blocked,accountStatus:!u.blocked?'stopped':u.accountStatus})},editUser:async id=>{const u=state.users[id],b=prompt('Balance',u.balance||0);if(b===null)return;const c=prompt('Commission',u.commission||0);if(c===null)return;await update(ref(db,`users/${id}`),{balance:Number(b),commission:Number(c)})},
 addLedger:async(uid,title,type,amount)=>{if(!uid||!Number.isFinite(amount))throw Error('UID and amount required');const signed=type==='debit'?-Math.abs(amount):Math.abs(amount),id=push(ref(db,`transactions/${uid}`)).key;await set(ref(db,`transactions/${uid}/${id}`),{title:title||'Ledger Entry',type,amount:signed,status:'completed',createdAt:Date.now()});if(type==='commission')await runTransaction(ref(db,`users/${uid}/commission`),v=>Number(v||0)+amount);else await runTransaction(ref(db,`users/${uid}/balance`),v=>Number(v||0)+signed)},
 addBonus:async uid=>{const amount=Number(state.settings.bonusAmount||2000),id=push(ref(db,`transactions/${uid}`)).key;await runTransaction(ref(db,`users/${uid}/balance`),v=>Number(v||0)+amount);await update(ref(db,`users/${uid}`),{bonusClaimed:true,bonusClaimedAt:Date.now()});await set(ref(db,`transactions/${uid}/${id}`),{title:'Admin Bonus',type:'bonus',amount,status:'completed',createdAt:Date.now()});alert('Bonus added')},resetBonus:uid=>update(ref(db,`users/${uid}`),{bonusClaimed:false,bonusClaimedAt:null}),
 saveFunds:d=>update(ref(db,'settings'),d),savePolicies:d=>update(ref(db,'settings'),d),saveSettings:d=>update(ref(db,'settings'),d),
 addBank:async name=>{if(!name)throw Error('Bank name required');const id=push(ref(db,'bankDirectory')).key;await set(ref(db,`bankDirectory/${id}`),{id,name,enabled:true})},toggleBank:(id,enable)=>update(ref(db,`bankDirectory/${id}`),{enabled:enable})
};
onAuthStateChanged(auth,async x=>{if(!x){state.loggedIn=false;emit();return}const a=await get(ref(db,`admins/${x.uid}`));if(!a.exists()||!['admin','superadmin'].includes(a.val().role)){await signOut(auth);return alert('Admin access denied')}me=x;state.loggedIn=true;state.adminEmail=x.email;emit();const on=(path,key,transform=v=>v||{})=>onValue(ref(db,path),s=>{state[key]=transform(s.val());emit()},e=>console.error(e));on('users','users');on('activationPayments','payments');on('withdrawals','withdrawals');on('settings','settings');on('adminActivityFeed','feed',v=>Object.values(v||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)));on('auditLogs','audits',v=>Object.values(v||{}).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)));on('fundAccounts','fundAccounts');on('transactions','transactions');on('bankDirectory','banks',v=>Object.entries(v||{}).map(([id,b])=>({id,...b})).sort((a,b)=>a.name.localeCompare(b.name)))});
mountAdmin(adapter);
