import{firebaseConfig}from"./firebase-config.js";

window.addEventListener("error",e=>console.error("Tiranga Pay error:",e.message,e.filename,e.lineno));
window.addEventListener("unhandledrejection",e=>console.error("Tiranga Pay promise error:",e.reason));

import{initializeApp}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import{getDatabase,ref,get,set,update,push,onValue}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js";
import{getMessaging,getToken}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-messaging.js";
const app=initializeApp(firebaseConfig);const auth=getAuth(app),db=getDatabase(app);let me=null,users={},payments={},withdrawals={},bonusClaims={},settings={},feed={},audits={};
const $=id=>document.getElementById(id),money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const menu=[["dashboard","Dashboard"],["users","Users List"],["payments","Payment Requests"],["funds","Fund Management"],["ledger","Transactions & Ledger"],["withdrawals","Withdrawals"],["bonus","Commission & Bonus"],["policies","Policies & App Content"],["notifications","Notifications"],["settings","General Settings"],["audit","Audit Logs"]];
$("menu").innerHTML=menu.map(([k,n],i)=>`<button class="${i===0?"active":""}" onclick="showPanel('${k}',this)">${n}</button>`).join("");
window.showPanel=(k,b)=>{document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));$(k).classList.add("active");document.querySelectorAll(".menu button").forEach(x=>x.classList.remove("active"));if(b)b.classList.add("active")};
window.adminLogin=async()=>{try{await signInWithEmailAndPassword(auth,$("adminEmail").value,$("adminPass").value)}catch(e){$("adminMsg").textContent=e.message}};window.adminLogout=()=>signOut(auth);
async function isAdmin(u){const s=await get(ref(db,"admins/"+u.uid));return s.exists()&&["admin","superadmin"].includes(s.val().role)}
async function audit(action,details={}){const k=push(ref(db,"auditLogs")).key;await set(ref(db,"auditLogs/"+k),{adminUid:me.uid,adminEmail:me.email,action,details,createdAt:Date.now()})}
async function userActivity(uid,type,title,message){const k=push(ref(db,"activityLogs/"+uid)).key;await set(ref(db,"activityLogs/"+uid+"/"+k),{type,title,message,createdAt:Date.now()})}
function render(){const ua=Object.values(users),pa=Object.values(payments),wa=Object.values(withdrawals),fa=Object.values(feed),ba=Object.values(bonusClaims);const kpis=[["Total Users",ua.length],["Total Balance",money(ua.reduce((a,x)=>a+Number(x.balance||0),0))],["Total Commission",money(ua.reduce((a,x)=>a+Number(x.commission||0),0))],["Pending Payments",pa.filter(x=>x.status==="pending").length],["Pending Withdrawals",wa.filter(x=>x.status==="pending").length],["Blocked Users",ua.filter(x=>x.blocked).length]];$("kpis").innerHTML=kpis.map(([n,v])=>`<div class="card kpi"><div class="label">${n}</div><b>${v}</b></div>`).join("");$("unread").textContent=fa.filter(x=>x.unread).length;
$("usersBody").innerHTML=Object.entries(users).map(([id,u])=>`<tr><td>${u.username||id.slice(0,8)}</td><td>${u.email||""}</td><td>${u.blocked?"Blocked":u.accountStatus||"Stopped"}</td><td>${u.invalidAttempts||0}/4</td><td>${money(u.penalty)}</td><td>${money(u.balance)}</td><td>${money(u.commission)}</td><td><button class="action" onclick="setState('${id}','running')">Run</button> <button class="action orange" onclick="setState('${id}','stopped')">Stop</button> <button class="action red" onclick="toggleBlock('${id}')">${u.blocked?"Unblock":"Block"}</button> <button class="action" onclick="editUser('${id}')">Edit</button></td></tr>`).join("");
const payHtml=Object.entries(payments).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0)).map(([id,p])=>`<div class="feeditem"><b>${p.email||id}</b><div class="label">${money(p.amount)} · UTR ${p.utr||""} · Attempt ${p.attempt||1}/4 · ${p.status}</div><button class="action" onclick="reviewPayment('${id}','approved')">Approve</button> <button class="action red" onclick="reviewPayment('${id}','rejected')">Reject Invalid UTR</button></div>`).join("");$("paymentsBody").innerHTML=payHtml||"No requests";$("dashPayments").innerHTML=payHtml.slice(0,1200);
$("withdrawalsBody").innerHTML=Object.entries(withdrawals).map(([id,w])=>`<div class="feeditem"><b>${w.email||w.uid}</b><div class="label">${money(w.amount)} · ${w.status}</div><button class="action" onclick="setWithdrawal('${id}','approved')">Approve</button> <button class="action orange" onclick="setWithdrawal('${id}','processing')">Processing</button> <button class="action" onclick="setWithdrawal('${id}','paid')">Paid</button> <button class="action red" onclick="setWithdrawal('${id}','rejected')">Reject</button></div>`).join("")||"No withdrawals";
$("bonusClaimsBody").innerHTML=Object.entries(bonusClaims).map(([id,b])=>`<div class="feeditem"><b>${b.email||b.uid}</b><div class="label">${money(b.amount)} · ${b.status}</div><button class="action" onclick="setBonusClaim('${id}','approved')">Approve</button> <button class="action red" onclick="setBonusClaim('${id}','rejected')">Reject</button></div>`).join("")||"No bonus claims";
const recent=Object.values(feed).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$("recentFeed").innerHTML=recent.slice(0,6).map(x=>`<div class="feeditem"><b>${x.title}</b><div class="label">${x.userEmail||""}</div></div>`).join("");$("adminFeed").innerHTML=Object.entries(feed).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0)).map(([id,x])=>`<div class="feeditem"><b>${x.title}</b><div>${x.message||""}</div><div class="label">${x.userEmail||""} · ${new Date(x.createdAt||0).toLocaleString("en-IN")}</div><button class="btn out" onclick="markRead('${id}')">Mark Read</button></div>`).join("");
$("statusOverview").innerHTML=`<p>Running: <b>${ua.filter(x=>x.accountStatus==="running").length}</b></p><p>Pending: <b>${ua.filter(x=>x.activationStatus==="pending").length}</b></p><p>Blocked: <b>${ua.filter(x=>x.blocked).length}</b></p>`;
const fk=[["gamingFundRate","Gaming Fund %",15],["stockFundRate","Stock Fund %",30],["mixFundRate","Mix Fund %",25],["politicalFundRate","Political Fund %",10],["outsideFundRate","Outside Fund %",20],["performanceBonusRate","Performance Bonus %",5]];$("fundForm").innerHTML=fk.map(([k,n,d])=>`<label>${n}<input id="${k}" type="number" value="${settings[k]??d}"></label>`).join("");
[["bonusAmount","bonusAmount"],["commissionRate","commissionRate"],["fundPolicy","fundPolicy"],["privacyPolicy","privacyPolicy"],["terms","terms"],["withdrawalPolicy","withdrawalPolicy"],["bonusPolicy","bonusPolicy"],["supportPolicy","supportPolicy"],["supportContact","supportContact"],["telegramLink","telegramLink"],["activationFee","activationFee"],["adminUpiId","adminUpiId"],["paymentQr","paymentQr"],["minWithdrawal","minWithdrawal"]].forEach(([id,k])=>{if($(id))$(id).value=settings[k]??""});
$("auditBody").innerHTML=Object.values(audits).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,100).map(a=>`<div class="feeditem"><b>${a.action}</b><div class="label">${a.adminEmail||""} · ${new Date(a.createdAt||0).toLocaleString("en-IN")}</div></div>`).join("")}
window.setState=async(id,s)=>{await update(ref(db,"users/"+id),{accountStatus:s,updatedAt:Date.now()});await userActivity(id,"account","Account status changed","Admin set account to "+s);await audit("USER_STATE",{id,s})};
window.toggleBlock=async id=>{const blocked=!users[id]?.blocked;await update(ref(db,"users/"+id),{blocked,accountStatus:blocked?"stopped":users[id]?.accountStatus||"stopped"});await userActivity(id,"account",blocked?"Account blocked":"Account unblocked",blocked?"Contact Support is still available.":"Account access restored.");await audit(blocked?"USER_BLOCKED":"USER_UNBLOCKED",{id})};
window.editUser=async id=>{const u=users[id]||{},b=prompt("Balance",u.balance||0);if(b===null)return;const c=prompt("Commission",u.commission||0);if(c===null)return;await update(ref(db,"users/"+id),{balance:Number(b),commission:Number(c)});await audit("USER_EDITED",{id,balance:b,commission:c})};
window.reviewPayment=async(id,status)=>{if(status==="approved"){const code="TP-"+Math.random().toString(36).slice(2,6).toUpperCase()+"-"+Date.now().toString().slice(-4);await update(ref(db,"activationPayments/"+id),{status:"approved",activationCode:code,reviewedAt:Date.now(),reviewedBy:me.uid});await update(ref(db,"users/"+id),{activationStatus:"approved"});await userActivity(id,"payment","Payment approved","Activation code is ready.");await audit("PAYMENT_APPROVED",{id,code})}else{const u=users[id]||{},next=Math.min(4,Number(u.invalidAttempts||0)+1),penalty=next===1?100:next===2?300:next===3?600:Number(u.penalty||600),blocked=next>=4,reason=prompt("Reject reason","Invalid/Fake UTR")||"Invalid/Fake UTR";await update(ref(db,"activationPayments/"+id),{status:"rejected",rejectReason:reason,reviewedAt:Date.now(),reviewedBy:me.uid});await update(ref(db,"users/"+id),{invalidAttempts:next,penalty,blocked,accountStatus:"stopped",activationStatus:"rejected"});await userActivity(id,"payment",blocked?"ID automatically blocked":"Payment rejected",blocked?"4 invalid attempts reached.":`Penalty updated. Total payable: ${money(Number(settings.activationFee||1999)+penalty)}`);await audit("PAYMENT_REJECTED",{id,next,penalty,blocked,reason})}};
window.setWithdrawal=async(id,s)=>{const w=withdrawals[id];await update(ref(db,"withdrawals/"+id),{status:s,updatedAt:Date.now()});if(w?.uid)await userActivity(w.uid,"withdrawal","Withdrawal "+s,money(w.amount)+" status updated.");await audit("WITHDRAWAL_"+s.toUpperCase(),{id})};
window.setBonusClaim=async(id,s)=>{const b=bonusClaims[id];await update(ref(db,"bonusClaims/"+id),{status:s,updatedAt:Date.now()});if(b?.uid)await userActivity(b.uid,"bonus","Bonus claim "+s,money(b.amount)+" status updated.");await audit("BONUS_"+s.toUpperCase(),{id})};
window.saveFunds=async()=>{const d={};["gamingFundRate","stockFundRate","mixFundRate","politicalFundRate","outsideFundRate","performanceBonusRate"].forEach(k=>d[k]=Number($(k).value));await update(ref(db,"settings"),d);await audit("FUND_SETTINGS_UPDATED",d);alert("Saved")};
window.addLedger=async()=>{const id=$("ledgerUid").value.trim(),amount=Number($("ledgerAmount").value),type=$("ledgerType").value;if(!id||!Number.isFinite(amount))return alert("UID and amount required");const k=push(ref(db,"transactions/"+id)).key;await set(ref(db,"transactions/"+id+"/"+k),{title:$("ledgerTitle").value||"Ledger Entry",type,amount,status:"completed",createdAt:Date.now(),createdBy:me.uid});const u=users[id]||{};if(type==="commission")await update(ref(db,"users/"+id),{commission:Number(u.commission||0)+amount});else await update(ref(db,"users/"+id),{balance:Number(u.balance||0)+amount});await userActivity(id,"transaction","Transaction updated",$("ledgerTitle").value||"Ledger entry added.");await audit("LEDGER_ADDED",{id,amount,type});alert("Added")};
window.saveBonusSettings=async()=>{const d={bonusAmount:Number($("bonusAmount").value||0),commissionRate:Number($("commissionRate").value||0)};await update(ref(db,"settings"),d);await audit("BONUS_SETTINGS_UPDATED",d);alert("Saved")};
window.savePolicies=async()=>{const d={fundPolicy:$("fundPolicy").value,privacyPolicy:$("privacyPolicy").value,terms:$("terms").value,withdrawalPolicy:$("withdrawalPolicy").value,bonusPolicy:$("bonusPolicy").value,supportPolicy:$("supportPolicy").value,supportContact:$("supportContact").value,telegramLink:$("telegramLink").value};await update(ref(db,"settings"),d);await audit("POLICIES_UPDATED",d);alert("Saved")};
window.saveGeneral=async()=>{const d={activationFee:Number($("activationFee").value||1999),adminUpiId:$("adminUpiId").value,paymentQr:$("paymentQr").value,minWithdrawal:Number($("minWithdrawal").value||0)};await update(ref(db,"settings"),d);await audit("GENERAL_SETTINGS_UPDATED",d);alert("Saved")};
window.sendNotification=async()=>{const title=$("notifyTitle").value.trim(),message=$("notifyMessage").value.trim(),uid=$("notifyUid").value.trim();if(!title||!message)return alert("Title and message required");const path=uid?"notifications/"+uid:"globalNotifications",k=push(ref(db,path)).key;await set(ref(db,path+"/"+k),{title,message,createdAt:Date.now(),createdBy:me.uid});await audit("NOTIFICATION_CREATED",{uid,title});alert("Notification saved")};
window.markRead=id=>update(ref(db,"adminActivityFeed/"+id),{unread:false});
window.allowNotifications=async()=>{try{const p=await Notification.requestPermission();if(p!=="granted")throw Error("Permission denied");if(!settings.webPushVapidKey)throw Error("VAPID key missing in settings");const reg=await navigator.serviceWorker.register("./firebase-messaging-sw.js"),m=getMessaging(app),token=await getToken(m,{vapidKey:settings.webPushVapidKey,serviceWorkerRegistration:reg});await set(ref(db,"adminFcmTokens/"+me.uid+"/"+Date.now()),{token,createdAt:Date.now(),userAgent:navigator.userAgent});alert("Notifications enabled")}catch(e){alert(e.message)}};
onAuthStateChanged(auth,async x=>{if(!x){$("loginView").classList.remove("hidden");$("panelView").classList.add("hidden");return}if(!(await isAdmin(x))){await signOut(auth);return $("adminMsg").textContent="Admin access denied"}me=x;$("adminIdentity").textContent=x.email;$("loginView").classList.add("hidden");$("panelView").classList.remove("hidden");onValue(ref(db,"users"),s=>{users=s.val()||{};render()});onValue(ref(db,"activationPayments"),s=>{payments=s.val()||{};render()});onValue(ref(db,"withdrawals"),s=>{withdrawals=s.val()||{};render()});onValue(ref(db,"bonusClaims"),s=>{bonusClaims=s.val()||{};render()});onValue(ref(db,"settings"),s=>{settings=s.val()||{};render()});onValue(ref(db,"adminActivityFeed"),s=>{feed=s.val()||{};render()});onValue(ref(db,"auditLogs"),s=>{audits=s.val()||{};render()})});